CREATE DATABASE TimeManager;

USE TimeManager;

CREATE TABLE IF NOT EXISTS Users (
UserSAKey INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UserName VARCHAR(128) NOT NULL,
PhoneNumber INT,
EmailAddress VARCHAR(128) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Task (
TaskSAKey INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TaskName VARCHAR(512) NOT NULL,
Description VARCHAR(1264) NULL,
Status INT NOT NULL,
CompletionDate TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS UserTasks (
UserTaskSAKey INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TaskSAKey INT NOT NULL,
UserSAKey INT NOT NULL
) ENGINE=INNODB;

ALTER TABLE UserTasks  
ADD CONSTRAINT FK_UserTaskSAKey
FOREIGN KEY (TaskSAKey) REFERENCES Task(TaskSAKey)
ON UPDATE CASCADE  
ON DELETE CASCADE;

ALTER TABLE UserTasks  
ADD CONSTRAINT FK_UserTaskSAKey
FOREIGN KEY (UserSAKey) REFERENCES Users(UserSAKey)
ON UPDATE CASCADE  
ON DELETE CASCADE;



--DROP TABLE Users

--DROP TABLE Task

--DROP TABLE UserTasks